// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import "../frb_generated.dart";
import "chats.dart";
import "messages.dart";
import "package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart";

// These functions are ignored because they are not marked as `pub`: `new_in_dir`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<App>>
abstract class App implements RustOpaqueInterface {
  Chats get chats;

  Messages get messages;

  set chats(Chats chats);

  set messages(Messages messages);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<App> newInstance() => RustLib.instance.api.crateAppAppAppNew();
}
