// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import "../frb_generated.dart";
import "package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart";

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DeleteAttachment`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`

class Attachment {
  final String path;
  final String fileName;

  const Attachment({required this.path, required this.fileName});

  @override
  int get hashCode => path.hashCode ^ fileName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Attachment &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          fileName == other.fileName;
}

class Chat {
  final int id;
  final String name;
  final Message? lastMessage;

  const Chat({required this.id, required this.name, this.lastMessage});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ lastMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Chat &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          lastMessage == other.lastMessage;
}

class DeleteChat {
  final int id;

  const DeleteChat({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteChat && runtimeType == other.runtimeType && id == other.id;
}

class DeleteMessage {
  final int chatId;
  final int id;

  const DeleteMessage({required this.chatId, required this.id});

  @override
  int get hashCode => chatId.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteMessage &&
          runtimeType == other.runtimeType &&
          chatId == other.chatId &&
          id == other.id;
}

class GetChat {
  final int id;

  const GetChat({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GetChat && runtimeType == other.runtimeType && id == other.id;
}

class GetMessage {
  final int chatId;
  final int id;

  const GetMessage({required this.chatId, required this.id});

  @override
  int get hashCode => chatId.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GetMessage &&
          runtimeType == other.runtimeType &&
          chatId == other.chatId &&
          id == other.id;
}

class ListChats {
  final int? lastMessageIdCursor;
  final int limit;
  final bool desc;

  const ListChats({
    this.lastMessageIdCursor,
    required this.limit,
    required this.desc,
  });

  @override
  int get hashCode =>
      lastMessageIdCursor.hashCode ^ limit.hashCode ^ desc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListChats &&
          runtimeType == other.runtimeType &&
          lastMessageIdCursor == other.lastMessageIdCursor &&
          limit == other.limit &&
          desc == other.desc;
}

class ListMessages {
  final int chatId;
  final int? id;
  final int limit;
  final bool desc;

  const ListMessages({
    required this.chatId,
    this.id,
    required this.limit,
    required this.desc,
  });

  @override
  int get hashCode =>
      chatId.hashCode ^ id.hashCode ^ limit.hashCode ^ desc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListMessages &&
          runtimeType == other.runtimeType &&
          chatId == other.chatId &&
          id == other.id &&
          limit == other.limit &&
          desc == other.desc;
}

class Message {
  final int id;
  final DateTime sentAt;
  final String text;
  final List<Attachment> attachments;

  const Message({
    required this.id,
    required this.sentAt,
    required this.text,
    required this.attachments,
  });

  @override
  int get hashCode =>
      id.hashCode ^ sentAt.hashCode ^ text.hashCode ^ attachments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sentAt == other.sentAt &&
          text == other.text &&
          attachments == other.attachments;
}

class PatchChat {
  final int id;
  final String? name;

  const PatchChat({required this.id, this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PatchChat &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class PatchMessage {
  final int chatId;
  final int id;
  final String? text;

  const PatchMessage({required this.chatId, required this.id, this.text});

  @override
  int get hashCode => chatId.hashCode ^ id.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PatchMessage &&
          runtimeType == other.runtimeType &&
          chatId == other.chatId &&
          id == other.id &&
          text == other.text;
}

class PostAttachment {
  final String path;

  const PostAttachment({required this.path});

  @override
  int get hashCode => path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PostAttachment &&
          runtimeType == other.runtimeType &&
          path == other.path;
}

class PostChat {
  final String name;

  const PostChat({required this.name});

  @override
  int get hashCode => name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PostChat &&
          runtimeType == other.runtimeType &&
          name == other.name;
}

class PostMessage {
  final int chatId;
  final String text;
  final List<PostAttachment> attachments;

  const PostMessage({
    required this.chatId,
    required this.text,
    required this.attachments,
  });

  @override
  int get hashCode => chatId.hashCode ^ text.hashCode ^ attachments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PostMessage &&
          runtimeType == other.runtimeType &&
          chatId == other.chatId &&
          text == other.text &&
          attachments == other.attachments;
}
