// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import "../frb_generated.dart";
import "dto.dart";
import "package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart";

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Messages>>
abstract class Messages implements RustOpaqueInterface {
  Future<bool> delete({required DeleteMessage request});

  Future<Message?> get_({required GetMessage request});

  Future<List<Message>> list({required ListMessages request});

  Future<Message> patch({required PatchMessage request});

  Future<Message> post({required PostMessage request});
}
