// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import "app/app.dart";
import "app/chats.dart";
import "app/dto.dart";
import "app/messages.dart";
import "dart:async";
import "dart:convert";
import "frb_generated.dart";
import "frb_generated.io.dart"
    if (dart.library.js_interop) "frb_generated.web.dart";
import "package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart";

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => "2.12.0";

  @override
  int get rustContentHash => 1397215190;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: "rust_lib_chattes",
        ioDirectory: "rust/target/release/",
        webPrefix: "pkg/",
        wasmBindgenName: "wasm_bindgen",
      );
}

abstract class RustLibApi extends BaseApi {
  Chats crateAppAppAppAutoAccessorGetChats({required App that});

  Messages crateAppAppAppAutoAccessorGetMessages({required App that});

  void crateAppAppAppAutoAccessorSetChats({
    required App that,
    required Chats chats,
  });

  void crateAppAppAppAutoAccessorSetMessages({
    required App that,
    required Messages messages,
  });

  Future<App> crateAppAppAppNew();

  Future<bool> crateAppChatsChatsDelete({
    required Chats that,
    required DeleteChat request,
  });

  Future<Chat?> crateAppChatsChatsGet({
    required Chats that,
    required GetChat request,
  });

  Future<List<Chat>> crateAppChatsChatsList({
    required Chats that,
    required ListChats request,
  });

  Future<Chat?> crateAppChatsChatsPatch({
    required Chats that,
    required PatchChat request,
  });

  Future<Chat> crateAppChatsChatsPost({
    required Chats that,
    required PostChat request,
  });

  Future<bool> crateAppMessagesMessagesDelete({
    required Messages that,
    required DeleteMessage request,
  });

  Future<Message?> crateAppMessagesMessagesGet({
    required Messages that,
    required GetMessage request,
  });

  Future<List<Message>> crateAppMessagesMessagesList({
    required Messages that,
    required ListMessages request,
  });

  Future<Message> crateAppMessagesMessagesPatch({
    required Messages that,
    required PatchMessage request,
  });

  Future<Message> crateAppMessagesMessagesPost({
    required Messages that,
    required PostMessage request,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_App;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_App;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AppPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Chats;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Chats;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ChatsPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Messages;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Messages;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MessagesPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Chats crateAppAppAppAutoAccessorGetChats({required App that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats,
          decodeErrorData: null,
        ),
        constMeta: kCrateAppAppAppAutoAccessorGetChatsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppAppAppAutoAccessorGetChatsConstMeta =>
      const TaskConstMeta(
        debugName: "App_auto_accessor_get_chats",
        argNames: ["that"],
      );

  @override
  Messages crateAppAppAppAutoAccessorGetMessages({required App that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages,
          decodeErrorData: null,
        ),
        constMeta: kCrateAppAppAppAutoAccessorGetMessagesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppAppAppAutoAccessorGetMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "App_auto_accessor_get_messages",
        argNames: ["that"],
      );

  @override
  void crateAppAppAppAutoAccessorSetChats({
    required App that,
    required Chats chats,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
            chats,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateAppAppAppAutoAccessorSetChatsConstMeta,
        argValues: [that, chats],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppAppAppAutoAccessorSetChatsConstMeta =>
      const TaskConstMeta(
        debugName: "App_auto_accessor_set_chats",
        argNames: ["that", "chats"],
      );

  @override
  void crateAppAppAppAutoAccessorSetMessages({
    required App that,
    required Messages messages,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
            messages,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateAppAppAppAutoAccessorSetMessagesConstMeta,
        argValues: [that, messages],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppAppAppAutoAccessorSetMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "App_auto_accessor_set_messages",
        argNames: ["that", "messages"],
      );

  @override
  Future<App> crateAppAppAppNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp,
          decodeErrorData: null,
        ),
        constMeta: kCrateAppAppAppNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppAppAppNewConstMeta =>
      const TaskConstMeta(debugName: "App_new", argNames: []);

  @override
  Future<bool> crateAppChatsChatsDelete({
    required Chats that,
    required DeleteChat request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
            that,
            serializer,
          );
          sse_encode_box_autoadd_delete_chat(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateAppChatsChatsDeleteConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppChatsChatsDeleteConstMeta => const TaskConstMeta(
    debugName: "Chats_delete",
    argNames: ["that", "request"],
  );

  @override
  Future<Chat?> crateAppChatsChatsGet({
    required Chats that,
    required GetChat request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
            that,
            serializer,
          );
          sse_encode_box_autoadd_get_chat(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_chat,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateAppChatsChatsGetConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppChatsChatsGetConstMeta => const TaskConstMeta(
    debugName: "Chats_get",
    argNames: ["that", "request"],
  );

  @override
  Future<List<Chat>> crateAppChatsChatsList({
    required Chats that,
    required ListChats request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
            that,
            serializer,
          );
          sse_encode_box_autoadd_list_chats(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateAppChatsChatsListConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppChatsChatsListConstMeta => const TaskConstMeta(
    debugName: "Chats_list",
    argNames: ["that", "request"],
  );

  @override
  Future<Chat?> crateAppChatsChatsPatch({
    required Chats that,
    required PatchChat request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
            that,
            serializer,
          );
          sse_encode_box_autoadd_patch_chat(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_chat,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateAppChatsChatsPatchConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppChatsChatsPatchConstMeta => const TaskConstMeta(
    debugName: "Chats_patch",
    argNames: ["that", "request"],
  );

  @override
  Future<Chat> crateAppChatsChatsPost({
    required Chats that,
    required PostChat request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
            that,
            serializer,
          );
          sse_encode_box_autoadd_post_chat(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chat,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateAppChatsChatsPostConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppChatsChatsPostConstMeta => const TaskConstMeta(
    debugName: "Chats_post",
    argNames: ["that", "request"],
  );

  @override
  Future<bool> crateAppMessagesMessagesDelete({
    required Messages that,
    required DeleteMessage request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
            that,
            serializer,
          );
          sse_encode_box_autoadd_delete_message(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateAppMessagesMessagesDeleteConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppMessagesMessagesDeleteConstMeta =>
      const TaskConstMeta(
        debugName: "Messages_delete",
        argNames: ["that", "request"],
      );

  @override
  Future<Message?> crateAppMessagesMessagesGet({
    required Messages that,
    required GetMessage request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
            that,
            serializer,
          );
          sse_encode_box_autoadd_get_message(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateAppMessagesMessagesGetConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppMessagesMessagesGetConstMeta =>
      const TaskConstMeta(
        debugName: "Messages_get",
        argNames: ["that", "request"],
      );

  @override
  Future<List<Message>> crateAppMessagesMessagesList({
    required Messages that,
    required ListMessages request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
            that,
            serializer,
          );
          sse_encode_box_autoadd_list_messages(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateAppMessagesMessagesListConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppMessagesMessagesListConstMeta =>
      const TaskConstMeta(
        debugName: "Messages_list",
        argNames: ["that", "request"],
      );

  @override
  Future<Message> crateAppMessagesMessagesPatch({
    required Messages that,
    required PatchMessage request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
            that,
            serializer,
          );
          sse_encode_box_autoadd_patch_message(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateAppMessagesMessagesPatchConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppMessagesMessagesPatchConstMeta =>
      const TaskConstMeta(
        debugName: "Messages_patch",
        argNames: ["that", "request"],
      );

  @override
  Future<Message> crateAppMessagesMessagesPost({
    required Messages that,
    required PostMessage request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
            that,
            serializer,
          );
          sse_encode_box_autoadd_post_message(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateAppMessagesMessagesPostConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAppMessagesMessagesPostConstMeta =>
      const TaskConstMeta(
        debugName: "Messages_post",
        argNames: ["that", "request"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_App => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_App => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Chats => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Chats => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Messages => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Messages => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  App
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Chats
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChatsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Messages
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessagesImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  App
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  App
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Chats
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChatsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Messages
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessagesImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      "Not implemented in this codec, please use the other one",
    );
  }

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeTimestamp(ts: dco_decode_i_64(raw).toInt(), isUtc: true);
  }

  @protected
  App
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Chats
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChatsImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Messages
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessagesImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Attachment dco_decode_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception("unexpected arr length: expect 2 but see ${arr.length}");
    return Attachment(
      path: dco_decode_String(arr[0]),
      fileName: dco_decode_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Chat dco_decode_box_autoadd_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chat(raw);
  }

  @protected
  DeleteChat dco_decode_box_autoadd_delete_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_delete_chat(raw);
  }

  @protected
  DeleteMessage dco_decode_box_autoadd_delete_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_delete_message(raw);
  }

  @protected
  GetChat dco_decode_box_autoadd_get_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_get_chat(raw);
  }

  @protected
  GetMessage dco_decode_box_autoadd_get_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_get_message(raw);
  }

  @protected
  ListChats dco_decode_box_autoadd_list_chats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_list_chats(raw);
  }

  @protected
  ListMessages dco_decode_box_autoadd_list_messages(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_list_messages(raw);
  }

  @protected
  Message dco_decode_box_autoadd_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_message(raw);
  }

  @protected
  PatchChat dco_decode_box_autoadd_patch_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_patch_chat(raw);
  }

  @protected
  PatchMessage dco_decode_box_autoadd_patch_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_patch_message(raw);
  }

  @protected
  PostChat dco_decode_box_autoadd_post_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_post_chat(raw);
  }

  @protected
  PostMessage dco_decode_box_autoadd_post_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_post_message(raw);
  }

  @protected
  Chat dco_decode_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception("unexpected arr length: expect 3 but see ${arr.length}");
    return Chat(
      id: dco_decode_CastedPrimitive_u_64(arr[0]),
      name: dco_decode_String(arr[1]),
      lastMessage: dco_decode_opt_box_autoadd_message(arr[2]),
    );
  }

  @protected
  DeleteChat dco_decode_delete_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception("unexpected arr length: expect 1 but see ${arr.length}");
    return DeleteChat(id: dco_decode_CastedPrimitive_u_64(arr[0]));
  }

  @protected
  DeleteMessage dco_decode_delete_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception("unexpected arr length: expect 2 but see ${arr.length}");
    return DeleteMessage(
      chatId: dco_decode_CastedPrimitive_u_64(arr[0]),
      id: dco_decode_CastedPrimitive_u_64(arr[1]),
    );
  }

  @protected
  GetChat dco_decode_get_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception("unexpected arr length: expect 1 but see ${arr.length}");
    return GetChat(id: dco_decode_CastedPrimitive_u_64(arr[0]));
  }

  @protected
  GetMessage dco_decode_get_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception("unexpected arr length: expect 2 but see ${arr.length}");
    return GetMessage(
      chatId: dco_decode_CastedPrimitive_u_64(arr[0]),
      id: dco_decode_CastedPrimitive_u_64(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<Attachment> dco_decode_list_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_attachment).toList();
  }

  @protected
  List<Chat> dco_decode_list_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat).toList();
  }

  @protected
  ListChats dco_decode_list_chats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception("unexpected arr length: expect 2 but see ${arr.length}");
    return ListChats(
      limit: dco_decode_u_32(arr[0]),
      desc: dco_decode_bool(arr[1]),
    );
  }

  @protected
  List<Message> dco_decode_list_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message).toList();
  }

  @protected
  ListMessages dco_decode_list_messages(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception("unexpected arr length: expect 4 but see ${arr.length}");
    return ListMessages(
      chatId: dco_decode_CastedPrimitive_u_64(arr[0]),
      id: dco_decode_opt_CastedPrimitive_u_64(arr[1]),
      limit: dco_decode_u_32(arr[2]),
      desc: dco_decode_bool(arr[3]),
    );
  }

  @protected
  List<PostAttachment> dco_decode_list_post_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_post_attachment).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Message dco_decode_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception("unexpected arr length: expect 4 but see ${arr.length}");
    return Message(
      id: dco_decode_CastedPrimitive_u_64(arr[0]),
      sentAt: dco_decode_Chrono_Utc(arr[1]),
      text: dco_decode_String(arr[2]),
      attachments: dco_decode_list_attachment(arr[3]),
    );
  }

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_CastedPrimitive_u_64(raw);
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Chat? dco_decode_opt_box_autoadd_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_chat(raw);
  }

  @protected
  Message? dco_decode_opt_box_autoadd_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_message(raw);
  }

  @protected
  PatchChat dco_decode_patch_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception("unexpected arr length: expect 2 but see ${arr.length}");
    return PatchChat(
      id: dco_decode_CastedPrimitive_u_64(arr[0]),
      name: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  PatchMessage dco_decode_patch_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception("unexpected arr length: expect 3 but see ${arr.length}");
    return PatchMessage(
      chatId: dco_decode_CastedPrimitive_u_64(arr[0]),
      id: dco_decode_CastedPrimitive_u_64(arr[1]),
      text: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  PostAttachment dco_decode_post_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception("unexpected arr length: expect 1 but see ${arr.length}");
    return PostAttachment(path: dco_decode_String(arr[0]));
  }

  @protected
  PostChat dco_decode_post_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception("unexpected arr length: expect 1 but see ${arr.length}");
    return PostChat(name: dco_decode_String(arr[0]));
  }

  @protected
  PostMessage dco_decode_post_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception("unexpected arr length: expect 3 but see ${arr.length}");
    return PostMessage(
      chatId: dco_decode_CastedPrimitive_u_64(arr[0]),
      text: dco_decode_String(arr[1]),
      attachments: dco_decode_list_post_attachment(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  App
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Chats
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ChatsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Messages
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MessagesImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  App
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  App
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Chats
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ChatsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Messages
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MessagesImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_u_64(deserializer);
    return inner.toInt();
  }

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return DateTime.fromMicrosecondsSinceEpoch(inner.toInt(), isUtc: true);
  }

  @protected
  App
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Chats
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ChatsImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Messages
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MessagesImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Attachment sse_decode_attachment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    return Attachment(path: var_path, fileName: var_fileName);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Chat sse_decode_box_autoadd_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chat(deserializer));
  }

  @protected
  DeleteChat sse_decode_box_autoadd_delete_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_delete_chat(deserializer));
  }

  @protected
  DeleteMessage sse_decode_box_autoadd_delete_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_delete_message(deserializer));
  }

  @protected
  GetChat sse_decode_box_autoadd_get_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_get_chat(deserializer));
  }

  @protected
  GetMessage sse_decode_box_autoadd_get_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_get_message(deserializer));
  }

  @protected
  ListChats sse_decode_box_autoadd_list_chats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_list_chats(deserializer));
  }

  @protected
  ListMessages sse_decode_box_autoadd_list_messages(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_list_messages(deserializer));
  }

  @protected
  Message sse_decode_box_autoadd_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_message(deserializer));
  }

  @protected
  PatchChat sse_decode_box_autoadd_patch_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_patch_chat(deserializer));
  }

  @protected
  PatchMessage sse_decode_box_autoadd_patch_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_patch_message(deserializer));
  }

  @protected
  PostChat sse_decode_box_autoadd_post_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_post_chat(deserializer));
  }

  @protected
  PostMessage sse_decode_box_autoadd_post_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_post_message(deserializer));
  }

  @protected
  Chat sse_decode_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_lastMessage = sse_decode_opt_box_autoadd_message(deserializer);
    return Chat(id: var_id, name: var_name, lastMessage: var_lastMessage);
  }

  @protected
  DeleteChat sse_decode_delete_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_CastedPrimitive_u_64(deserializer);
    return DeleteChat(id: var_id);
  }

  @protected
  DeleteMessage sse_decode_delete_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chatId = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_id = sse_decode_CastedPrimitive_u_64(deserializer);
    return DeleteMessage(chatId: var_chatId, id: var_id);
  }

  @protected
  GetChat sse_decode_get_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_CastedPrimitive_u_64(deserializer);
    return GetChat(id: var_id);
  }

  @protected
  GetMessage sse_decode_get_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chatId = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_id = sse_decode_CastedPrimitive_u_64(deserializer);
    return GetMessage(chatId: var_chatId, id: var_id);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<Attachment> sse_decode_list_attachment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Attachment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_attachment(deserializer));
    }
    return ans_;
  }

  @protected
  List<Chat> sse_decode_list_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Chat>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat(deserializer));
    }
    return ans_;
  }

  @protected
  ListChats sse_decode_list_chats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_limit = sse_decode_u_32(deserializer);
    var var_desc = sse_decode_bool(deserializer);
    return ListChats(limit: var_limit, desc: var_desc);
  }

  @protected
  List<Message> sse_decode_list_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Message>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message(deserializer));
    }
    return ans_;
  }

  @protected
  ListMessages sse_decode_list_messages(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chatId = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_id = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_limit = sse_decode_u_32(deserializer);
    var var_desc = sse_decode_bool(deserializer);
    return ListMessages(
      chatId: var_chatId,
      id: var_id,
      limit: var_limit,
      desc: var_desc,
    );
  }

  @protected
  List<PostAttachment> sse_decode_list_post_attachment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PostAttachment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_post_attachment(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Message sse_decode_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_sentAt = sse_decode_Chrono_Utc(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_attachments = sse_decode_list_attachment(deserializer);
    return Message(
      id: var_id,
      sentAt: var_sentAt,
      text: var_text,
      attachments: var_attachments,
    );
  }

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_CastedPrimitive_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Chat? sse_decode_opt_box_autoadd_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_chat(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Message? sse_decode_opt_box_autoadd_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_message(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PatchChat sse_decode_patch_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    return PatchChat(id: var_id, name: var_name);
  }

  @protected
  PatchMessage sse_decode_patch_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chatId = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_id = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    return PatchMessage(chatId: var_chatId, id: var_id, text: var_text);
  }

  @protected
  PostAttachment sse_decode_post_attachment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    return PostAttachment(path: var_path);
  }

  @protected
  PostChat sse_decode_post_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    return PostChat(name: var_name);
  }

  @protected
  PostMessage sse_decode_post_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chatId = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_attachments = sse_decode_list_post_attachment(deserializer);
    return PostMessage(
      chatId: var_chatId,
      text: var_text,
      attachments: var_attachments,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    App self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    Chats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ChatsImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    Messages self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MessagesImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    App self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    App self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    Chats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ChatsImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    Messages self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MessagesImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(
      PlatformInt64Util.from(self.microsecondsSinceEpoch),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    App self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    Chats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ChatsImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    Messages self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MessagesImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_attachment(Attachment self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.fileName, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_chat(Chat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chat(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_delete_chat(
    DeleteChat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_delete_chat(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_delete_message(
    DeleteMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_delete_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_get_chat(GetChat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_get_chat(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_get_message(
    GetMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_get_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_list_chats(
    ListChats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_chats(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_list_messages(
    ListMessages self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_messages(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_message(Message self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_patch_chat(
    PatchChat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_patch_chat(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_patch_message(
    PatchMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_patch_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_post_chat(
    PostChat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_post_chat(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_post_message(
    PostMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_post_message(self, serializer);
  }

  @protected
  void sse_encode_chat(Chat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_box_autoadd_message(self.lastMessage, serializer);
  }

  @protected
  void sse_encode_delete_chat(DeleteChat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.id, serializer);
  }

  @protected
  void sse_encode_delete_message(DeleteMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.chatId, serializer);
    sse_encode_CastedPrimitive_u_64(self.id, serializer);
  }

  @protected
  void sse_encode_get_chat(GetChat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.id, serializer);
  }

  @protected
  void sse_encode_get_message(GetMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.chatId, serializer);
    sse_encode_CastedPrimitive_u_64(self.id, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_attachment(
    List<Attachment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_attachment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chat(List<Chat> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chats(ListChats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.limit, serializer);
    sse_encode_bool(self.desc, serializer);
  }

  @protected
  void sse_encode_list_message(List<Message> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_messages(ListMessages self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.chatId, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.id, serializer);
    sse_encode_u_32(self.limit, serializer);
    sse_encode_bool(self.desc, serializer);
  }

  @protected
  void sse_encode_list_post_attachment(
    List<PostAttachment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_post_attachment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_message(Message self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.id, serializer);
    sse_encode_Chrono_Utc(self.sentAt, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_list_attachment(self.attachments, serializer);
  }

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(
    int? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_CastedPrimitive_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_chat(Chat? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_chat(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_message(
    Message? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_message(self, serializer);
    }
  }

  @protected
  void sse_encode_patch_chat(PatchChat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.id, serializer);
    sse_encode_opt_String(self.name, serializer);
  }

  @protected
  void sse_encode_patch_message(PatchMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.chatId, serializer);
    sse_encode_CastedPrimitive_u_64(self.id, serializer);
    sse_encode_opt_String(self.text, serializer);
  }

  @protected
  void sse_encode_post_attachment(
    PostAttachment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
  }

  @protected
  void sse_encode_post_chat(PostChat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_post_message(PostMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.chatId, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_list_post_attachment(self.attachments, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class AppImpl extends RustOpaque implements App {
  // Not to be used by end users
  AppImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AppImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_App,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_App,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AppPtr,
  );

  Chats get chats =>
      RustLib.instance.api.crateAppAppAppAutoAccessorGetChats(that: this);

  Messages get messages =>
      RustLib.instance.api.crateAppAppAppAutoAccessorGetMessages(that: this);

  set chats(Chats chats) => RustLib.instance.api
      .crateAppAppAppAutoAccessorSetChats(that: this, chats: chats);

  set messages(Messages messages) => RustLib.instance.api
      .crateAppAppAppAutoAccessorSetMessages(that: this, messages: messages);
}

@sealed
class ChatsImpl extends RustOpaque implements Chats {
  // Not to be used by end users
  ChatsImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ChatsImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Chats,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Chats,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ChatsPtr,
  );

  Future<bool> delete({required DeleteChat request}) => RustLib.instance.api
      .crateAppChatsChatsDelete(that: this, request: request);

  Future<Chat?> get_({required GetChat request}) =>
      RustLib.instance.api.crateAppChatsChatsGet(that: this, request: request);

  Future<List<Chat>> list({required ListChats request}) =>
      RustLib.instance.api.crateAppChatsChatsList(that: this, request: request);

  Future<Chat?> patch({required PatchChat request}) => RustLib.instance.api
      .crateAppChatsChatsPatch(that: this, request: request);

  Future<Chat> post({required PostChat request}) =>
      RustLib.instance.api.crateAppChatsChatsPost(that: this, request: request);
}

@sealed
class MessagesImpl extends RustOpaque implements Messages {
  // Not to be used by end users
  MessagesImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MessagesImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Messages,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Messages,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_MessagesPtr,
  );

  Future<bool> delete({required DeleteMessage request}) => RustLib.instance.api
      .crateAppMessagesMessagesDelete(that: this, request: request);

  Future<Message?> get_({required GetMessage request}) => RustLib.instance.api
      .crateAppMessagesMessagesGet(that: this, request: request);

  Future<List<Message>> list({required ListMessages request}) => RustLib
      .instance
      .api
      .crateAppMessagesMessagesList(that: this, request: request);

  Future<Message> patch({required PatchMessage request}) => RustLib.instance.api
      .crateAppMessagesMessagesPatch(that: this, request: request);

  Future<Message> post({required PostMessage request}) => RustLib.instance.api
      .crateAppMessagesMessagesPost(that: this, request: request);
}
