// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import "../frb_generated.dart";
import "dto.dart";
import "package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart";

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Chats>>
abstract class Chats implements RustOpaqueInterface {
  Future<bool> delete({required DeleteChat request});

  Future<Chat?> get_({required GetChat request});

  Future<List<Chat>> list({required ListChats request});

  Future<Chat?> patch({required PatchChat request});

  Future<Chat> post({required PostChat request});
}
