// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import "app/app.dart";
import "app/chats.dart";
import "app/dto.dart";
import "app/messages.dart";
import "dart:async";
import "dart:convert";
import "dart:ffi" as ffi;
import "frb_generated.dart";
import "package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart";

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AppPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ChatsPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatsPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MessagesPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessagesPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  App
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    dynamic raw,
  );

  @protected
  Chats
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    dynamic raw,
  );

  @protected
  Messages
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    dynamic raw,
  );

  @protected
  App
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    dynamic raw,
  );

  @protected
  App
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    dynamic raw,
  );

  @protected
  Chats
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    dynamic raw,
  );

  @protected
  Messages
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    dynamic raw,
  );

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  App
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    dynamic raw,
  );

  @protected
  Chats
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    dynamic raw,
  );

  @protected
  Messages
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Attachment dco_decode_attachment(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Chat dco_decode_box_autoadd_chat(dynamic raw);

  @protected
  DeleteChat dco_decode_box_autoadd_delete_chat(dynamic raw);

  @protected
  DeleteMessage dco_decode_box_autoadd_delete_message(dynamic raw);

  @protected
  GetChat dco_decode_box_autoadd_get_chat(dynamic raw);

  @protected
  GetMessage dco_decode_box_autoadd_get_message(dynamic raw);

  @protected
  ListChats dco_decode_box_autoadd_list_chats(dynamic raw);

  @protected
  ListMessages dco_decode_box_autoadd_list_messages(dynamic raw);

  @protected
  Message dco_decode_box_autoadd_message(dynamic raw);

  @protected
  PatchChat dco_decode_box_autoadd_patch_chat(dynamic raw);

  @protected
  PatchMessage dco_decode_box_autoadd_patch_message(dynamic raw);

  @protected
  PostChat dco_decode_box_autoadd_post_chat(dynamic raw);

  @protected
  PostMessage dco_decode_box_autoadd_post_message(dynamic raw);

  @protected
  Chat dco_decode_chat(dynamic raw);

  @protected
  DeleteChat dco_decode_delete_chat(dynamic raw);

  @protected
  DeleteMessage dco_decode_delete_message(dynamic raw);

  @protected
  GetChat dco_decode_get_chat(dynamic raw);

  @protected
  GetMessage dco_decode_get_message(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<Attachment> dco_decode_list_attachment(dynamic raw);

  @protected
  List<Chat> dco_decode_list_chat(dynamic raw);

  @protected
  ListChats dco_decode_list_chats(dynamic raw);

  @protected
  List<Message> dco_decode_list_message(dynamic raw);

  @protected
  ListMessages dco_decode_list_messages(dynamic raw);

  @protected
  List<PostAttachment> dco_decode_list_post_attachment(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Message dco_decode_message(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Chat? dco_decode_opt_box_autoadd_chat(dynamic raw);

  @protected
  Message? dco_decode_opt_box_autoadd_message(dynamic raw);

  @protected
  PatchChat dco_decode_patch_chat(dynamic raw);

  @protected
  PatchMessage dco_decode_patch_message(dynamic raw);

  @protected
  PostAttachment dco_decode_post_attachment(dynamic raw);

  @protected
  PostChat dco_decode_post_chat(dynamic raw);

  @protected
  PostMessage dco_decode_post_message(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  App
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    SseDeserializer deserializer,
  );

  @protected
  Chats
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    SseDeserializer deserializer,
  );

  @protected
  Messages
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    SseDeserializer deserializer,
  );

  @protected
  App
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    SseDeserializer deserializer,
  );

  @protected
  App
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    SseDeserializer deserializer,
  );

  @protected
  Chats
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    SseDeserializer deserializer,
  );

  @protected
  Messages
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  App
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    SseDeserializer deserializer,
  );

  @protected
  Chats
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    SseDeserializer deserializer,
  );

  @protected
  Messages
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Attachment sse_decode_attachment(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Chat sse_decode_box_autoadd_chat(SseDeserializer deserializer);

  @protected
  DeleteChat sse_decode_box_autoadd_delete_chat(SseDeserializer deserializer);

  @protected
  DeleteMessage sse_decode_box_autoadd_delete_message(
    SseDeserializer deserializer,
  );

  @protected
  GetChat sse_decode_box_autoadd_get_chat(SseDeserializer deserializer);

  @protected
  GetMessage sse_decode_box_autoadd_get_message(SseDeserializer deserializer);

  @protected
  ListChats sse_decode_box_autoadd_list_chats(SseDeserializer deserializer);

  @protected
  ListMessages sse_decode_box_autoadd_list_messages(
    SseDeserializer deserializer,
  );

  @protected
  Message sse_decode_box_autoadd_message(SseDeserializer deserializer);

  @protected
  PatchChat sse_decode_box_autoadd_patch_chat(SseDeserializer deserializer);

  @protected
  PatchMessage sse_decode_box_autoadd_patch_message(
    SseDeserializer deserializer,
  );

  @protected
  PostChat sse_decode_box_autoadd_post_chat(SseDeserializer deserializer);

  @protected
  PostMessage sse_decode_box_autoadd_post_message(SseDeserializer deserializer);

  @protected
  Chat sse_decode_chat(SseDeserializer deserializer);

  @protected
  DeleteChat sse_decode_delete_chat(SseDeserializer deserializer);

  @protected
  DeleteMessage sse_decode_delete_message(SseDeserializer deserializer);

  @protected
  GetChat sse_decode_get_chat(SseDeserializer deserializer);

  @protected
  GetMessage sse_decode_get_message(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<Attachment> sse_decode_list_attachment(SseDeserializer deserializer);

  @protected
  List<Chat> sse_decode_list_chat(SseDeserializer deserializer);

  @protected
  ListChats sse_decode_list_chats(SseDeserializer deserializer);

  @protected
  List<Message> sse_decode_list_message(SseDeserializer deserializer);

  @protected
  ListMessages sse_decode_list_messages(SseDeserializer deserializer);

  @protected
  List<PostAttachment> sse_decode_list_post_attachment(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Message sse_decode_message(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Chat? sse_decode_opt_box_autoadd_chat(SseDeserializer deserializer);

  @protected
  Message? sse_decode_opt_box_autoadd_message(SseDeserializer deserializer);

  @protected
  PatchChat sse_decode_patch_chat(SseDeserializer deserializer);

  @protected
  PatchMessage sse_decode_patch_message(SseDeserializer deserializer);

  @protected
  PostAttachment sse_decode_post_attachment(SseDeserializer deserializer);

  @protected
  PostChat sse_decode_post_chat(SseDeserializer deserializer);

  @protected
  PostMessage sse_decode_post_message(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    App self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    Chats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    Messages self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    App self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    App self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    Chats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    Messages self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    App self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    Chats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    Messages self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_attachment(Attachment self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_chat(Chat self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_delete_chat(
    DeleteChat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_delete_message(
    DeleteMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_get_chat(GetChat self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_get_message(
    GetMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_chats(
    ListChats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_messages(
    ListMessages self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_message(Message self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_patch_chat(
    PatchChat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_patch_message(
    PatchMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_post_chat(
    PostChat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_post_message(
    PostMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat(Chat self, SseSerializer serializer);

  @protected
  void sse_encode_delete_chat(DeleteChat self, SseSerializer serializer);

  @protected
  void sse_encode_delete_message(DeleteMessage self, SseSerializer serializer);

  @protected
  void sse_encode_get_chat(GetChat self, SseSerializer serializer);

  @protected
  void sse_encode_get_message(GetMessage self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_attachment(
    List<Attachment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chat(List<Chat> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chats(ListChats self, SseSerializer serializer);

  @protected
  void sse_encode_list_message(List<Message> self, SseSerializer serializer);

  @protected
  void sse_encode_list_messages(ListMessages self, SseSerializer serializer);

  @protected
  void sse_encode_list_post_attachment(
    List<PostAttachment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message(Message self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_chat(Chat? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_message(
    Message? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_patch_chat(PatchChat self, SseSerializer serializer);

  @protected
  void sse_encode_patch_message(PatchMessage self, SseSerializer serializer);

  @protected
  void sse_encode_post_attachment(
    PostAttachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_post_chat(PostChat self, SseSerializer serializer);

  @protected
  void sse_encode_post_message(PostMessage self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        "frbgen_chattes_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp",
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        "frbgen_chattes_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp",
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApp =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        "frbgen_chattes_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats",
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatsPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        "frbgen_chattes_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats",
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChats =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatsPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessagesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        "frbgen_chattes_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages",
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessagesPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessagesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        "frbgen_chattes_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages",
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessages =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessagesPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
